#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when apcupsd
# detects that the battery should be replaced.
# We send an email message to root to notify him.
#

#HOSTNAME=`hostname`
#MSG="$HOSTNAME UPS $1 battery needs changing NOW."
#
#(
#   echo "Subject: $MSG"
#   echo " "
#   echo "$MSG"
#   echo " "
#   /usr/bin/apcaccess status
#) | $APCUPSD_MAIL -s "$MSG" $SYSADMIN

/opt/motion/send_event.sh -f -i ups "UPS Change battery"
#/opt/motion/on_send_sms.sh ups_pwr_lost "UPS Lost connection" force

exit 0
